/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class conemu_jni_ConEmuPipeServer_N */

#ifndef _Included_conemu_jni_ConEmuPipeServer_N
#define _Included_conemu_jni_ConEmuPipeServer_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     conemu_jni_ConEmuPipeServer_N
 * Method:    runPipeServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_conemu_jni_ConEmuPipeServer_1N_runPipeServer(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
