/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class conemu_jni_GuiMacroExecutor_N */

#ifndef _Included_conemu_jni_GuiMacroExecutor_N
#define _Included_conemu_jni_GuiMacroExecutor_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     conemu_jni_GuiMacroExecutor_N
 * Method:    N_LoadConEmuDll
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_conemu_jni_GuiMacroExecutor_1N_N_1LoadConEmuDll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     conemu_jni_GuiMacroExecutor_N
 * Method:    N_InitGuiMacroFn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_conemu_jni_GuiMacroExecutor_1N_N_1InitGuiMacroFn
  (JNIEnv *, jobject);

/*
 * Class:     conemu_jni_GuiMacroExecutor_N
 * Method:    N_ExecuteInProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_conemu_jni_GuiMacroExecutor_1N_N_1ExecuteInProcess
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
