/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <windows.h>
/* Header for class ideaconemu_JNIHelper */

#ifndef _Included_ideaconemu_JNIHelper
#define _Included_ideaconemu_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ideaconemu_JNIHelper
 * Method:    N_SetParent
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ideaconemu_JNIHelper_N_1SetParent
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
