/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_jni_GuiMacroExecutor_N */

#ifndef _Included_org_iceterm_jni_GuiMacroExecutor_N
#define _Included_org_iceterm_jni_GuiMacroExecutor_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_jni_GuiMacroExecutor_N
 * Method:    N_LoadConEmuDll
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_iceterm_jni_GuiMacroExecutor_1N_N_1LoadConEmuDll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_iceterm_jni_GuiMacroExecutor_N
 * Method:    N_InitGuiMacroFn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_iceterm_jni_GuiMacroExecutor_1N_N_1InitGuiMacroFn
  (JNIEnv *, jobject);

/*
 * Class:     org_iceterm_jni_GuiMacroExecutor_N
 * Method:    N_ExecuteInProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_iceterm_jni_GuiMacroExecutor_1N_N_1ExecuteInProcess
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_iceterm_jni_GuiMacroExecutor_N
 * Method:    N_RunPipeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iceterm_jni_GuiMacroExecutor_1N_N_1RunPipeServer
  (JNIEnv *, jclass);

/*
 * Class:     org_iceterm_jni_GuiMacroExecutor_N
 * Method:    N_RunPipeClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_iceterm_jni_GuiMacroExecutor_1N_N_1RunPipeClient
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
