/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_jni_ConEmuPipeServer_N */

#ifndef _Included_org_iceterm_jni_ConEmuPipeServer_N
#define _Included_org_iceterm_jni_ConEmuPipeServer_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_jni_ConEmuPipeServer_N
 * Method:    N_RunPipeServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iceterm_jni_ConEmuPipeServer_1N_N_1RunPipeServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
