/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_ceintegration_GuiMacroExecutor */

#ifndef _Included_org_iceterm_ceintegration_GuiMacroExecutor
#define _Included_org_iceterm_ceintegration_GuiMacroExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_ceintegration_GuiMacroExecutor
 * Method:    loadConEmuDll
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_iceterm_ceintegration_GuiMacroExecutor_loadConEmuDll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_iceterm_ceintegration_GuiMacroExecutor
 * Method:    initGuiMacroFn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_iceterm_ceintegration_GuiMacroExecutor_initGuiMacroFn
  (JNIEnv *, jobject);

/*
 * Class:     org_iceterm_ceintegration_GuiMacroExecutor
 * Method:    executeInProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_iceterm_ceintegration_GuiMacroExecutor_executeInProcess
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
