/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_conemu_hook_ConEmuPipe */

#ifndef _Included_org_iceterm_conemu_hook_ConEmuPipe
#define _Included_org_iceterm_conemu_hook_ConEmuPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_conemu_hook_ConEmuPipe
 * Method:    runPipeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_ConEmuHook_runPipeServer
  (JNIEnv *, jclass);

/*
 * Class:     org_iceterm_conemu_hook_ConEmuPipe
 * Method:    runPipeClient
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_ConEmuHook_inject
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
