/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_cehook_GlobalScreen */

#ifndef _Included_org_iceterm_cehook_GlobalScreen
#define _Included_org_iceterm_cehook_GlobalScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_cehook_GlobalScreen
 * Method:    postNativeEvent
 * Signature: (Lorg/iceterm/cehook/NativeInputEvent;)V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_GlobalScreen_postNativeEvent
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
