/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iceterm_cehook_ConEmuHook */

#ifndef _Included_org_iceterm_cehook_ConEmuHook
#define _Included_org_iceterm_cehook_ConEmuHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iceterm_cehook_ConEmuHook
 * Method:    runPipeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_ConEmuHook_createPipeServer
  (JNIEnv *, jclass);

/*
 * Class:     org_iceterm_cehook_ConEmuHook
 * Method:    runPipeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_ConEmuHook_runPipeServer
        (JNIEnv *, jclass);


/*
 * Class:     org_iceterm_cehook_ConEmuHook
 * Method:    runPipeClient
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_iceterm_cehook_ConEmuHook_inject
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
